### ISSUE TITLE
[DOXIASITETOOLS-13] NPE when generating Maven site

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doxia-sitetools#318]
**[Adrian Tarau](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adrian.tarau)** opened **[DOXIASITETOOLS-13](https://issues.apache.org/jira/browse/DOXIASITETOOLS-13?redirect=false)** and commented

Recently we moved on M2 & Hudson. On our build server(SunOS) it fails with this exception, but on my machine(Ubuntu 8.04, Linux 2.6.24-19-386 i686 GNU/Linux) it works great.

java.lang.NullPointerException
at org.apache.maven.doxia.site.decoration.inheritance.PathUtils.getRelativePath(PathUtils.java:83)
at org.apache.maven.doxia.site.decoration.inheritance.PathUtils.convertPath(PathUtils.java:43)
at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.convertPath(DefaultDecorationModelInheritanceAssembler.java:334)
at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.resolveLinkItemPaths(DefaultDecorationModelInheritanceAssembler.java:255)
at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.mergeLinkItemLists(DefaultDecorationModelInheritanceAssembler.java:277)
at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.assembleBodyInheritance(DefaultDecorationModelInheritanceAssembler.java:192)
at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.assembleModelInheritance(DefaultDecorationModelInheritanceAssembler.java:83)
at org.apache.maven.plugins.site.AbstractSiteRenderingMojo.getDecorationModel(AbstractSiteRenderingMojo.java:253)
at org.apache.maven.plugins.site.AbstractSiteRenderingMojo.getDecorationModel(AbstractSiteRenderingMojo.java:527)
at org.apache.maven.plugins.site.AbstractSiteRenderingMojo.createSiteRenderingContext(AbstractSiteRenderingMojo.java:466)
at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:113)
at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:96)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
at hudson.maven.agent.PluginManagerInterceptor.executeMojo(PluginManagerInterceptor.java:159)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
at org.apache.maven.lifecycle.LifecycleExecutorInterceptor.execute(LifecycleExecutorInterceptor.java:42)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:585)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at hudson.maven.agent.Main.launch(Main.java:133)
at hudson.maven.MavenBuilder.call(MavenBuilder.java:139)
at hudson.maven.MavenModuleSetBuild$Builder.call(MavenModuleSetBuild.java:543)
at hudson.maven.MavenModuleSetBuild$Builder.call(MavenModuleSetBuild.java:489)
at hudson.remoting.UserRequest.perform(UserRequest.java:69)
at hudson.remoting.UserRequest.perform(UserRequest.java:23)
at hudson.remoting.Request$2.run(Request.java:213)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:417)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:269)
at java.util.concurrent.FutureTask.run(FutureTask.java:123)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:650)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:675)
at java.lang.Thread.run(Thread.java:595)

---

**Attachments:**
- [Fixed_NPE_when_old_path_is_an_URL_and_new_path_is_NULL.patch](https://issues.apache.org/jira/secure/attachment/12715667/Fixed_NPE_when_old_path_is_an_URL_and_new_path_is_NULL.patch) (_1.40 kB_)

**Issue Links:**
- [DOXIASITETOOLS-16](https://issues.apache.org/jira/browse/DOXIASITETOOLS-16) NullPointerException
 (_**"is duplicated by"**_)
- [MSITE-311](https://issues.apache.org/jira/browse/MSITE-311) NPE on absolute URLs if project.url not defined
 (_**"supercedes"**_)

**Backported to:** [1.0](https://github.com/apache/maven-doxia-sitetools/milestone/5?closed=1)

**Comment by jira-importer** [comment]
**[Adrian Tarau](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adrian.tarau)** commented

There is another report here http://jira.codehaus.org/browse/MSITE-311

**Comment by jira-importer** [comment]
**[Adrian Tarau](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=adrian.tarau)** commented

This fix works for me

**Comment by jira-importer** [comment]
**[Lukas Theussl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ltheussl)** commented

Patch applied in r732668. Thanks!
