### ISSUE TITLE
[DOXIASITETOOLS-16] NullPointerException

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doxia-sitetools#320]
**[Valerio Schiavoni](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vschiavoni)** opened **[DOXIASITETOOLS-16](https://issues.apache.org/jira/browse/DOXIASITETOOLS-16?redirect=false)** and commented

I get this stacktrace:
[INFO] [INFO] [site:site]
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [ERROR] FATAL ERROR
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] null
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Trace
[INFO] java.lang.NullPointerException
[INFO] 	at org.apache.maven.doxia.site.decoration.inheritance.PathUtils.getRelativePath(PathUtils.java:83)
[INFO] 	at org.apache.maven.doxia.site.decoration.inheritance.PathUtils.convertPath(PathUtils.java:43)
[INFO] 	at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.convertPath(DefaultDecorationModelInheritanceAssembler.java:334)
[INFO] 	at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.resolveLinkItemPaths(DefaultDecorationModelInheritanceAssembler.java:255)
[INFO] 	at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.mergeLinkItemLists(DefaultDecorationModelInheritanceAssembler.java:277)
[INFO] 	at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.assembleBodyInheritance(DefaultDecorationModelInheritanceAssembler.java:192)
[INFO] 	at org.apache.maven.doxia.site.decoration.inheritance.DefaultDecorationModelInheritanceAssembler.assembleModelInheritance(DefaultDecorationModelInheritanceAssembler.java:83)
[INFO] 	at org.apache.maven.plugins.site.AbstractSiteRenderingMojo.getDecorationModel(AbstractSiteRenderingMojo.java:253)
[INFO] 	at org.apache.maven.plugins.site.AbstractSiteRenderingMojo.getDecorationModel(AbstractSiteRenderingMojo.java:527)
[INFO] 	at org.apache.maven.plugins.site.AbstractSiteRenderingMojo.createSiteRenderingContext(AbstractSiteRenderingMojo.java:466)
[INFO] 	at org.apache.maven.plugins.site.SiteMojo.renderLocale(SiteMojo.java:113)
[INFO] 	at org.apache.maven.plugins.site.SiteMojo.execute(SiteMojo.java:96)
[INFO] 	at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:451)
[INFO] 	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:558)
[INFO] 	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:499)
[INFO] 	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:478)
[INFO] 	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:330)
[INFO] 	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:291)
[INFO] 	at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:142)
[INFO] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:336)
[INFO] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:129)
[INFO] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:287)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:585)
[INFO] 	at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
[INFO] 	at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
[INFO] 	at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
[INFO] 	at org.codehaus.classworlds.Launcher.main(Launcher.java:375)

I'm using the latest released maven site plugin.

---

**Issue Links:**
- [DOXIASITETOOLS-13](https://issues.apache.org/jira/browse/DOXIASITETOOLS-13) NPE when generating Maven site
 (_**"duplicates"**_)
- [MSITE-263](https://issues.apache.org/jira/browse/MSITE-263) NullPointerException if build run from a module and no url defined in module or parent

**Comment by jira-importer** [comment]
**[Valerio Schiavoni](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vschiavoni)** commented

The stacktrace is a result of the command:
mvn release:perform -e -DconnectionUrl=scm:svn:svn+ssh://svn.forge.objectweb.org/svnroot/fractal/tags/FRACTAL_BF_0_5

The pom files causing the stacktrace are freely accessible by browsing the SVN:
http://svn.forge.objectweb.org/cgi-bin/viewcvs.cgi/fractal/tags/FRACTAL_BF_0_5/

and the module that it causing the failire is:
http://svn.forge.objectweb.org/cgi-bin/viewcvs.cgi/fractal/tags/FRACTAL_BF_0_5/core/pom.xml?rev=9145&view=markup

**Comment by jira-importer** [comment]
**[Valerio Schiavoni](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vschiavoni)** commented

Reading a run with -X option, more informations are discovered:

Configuring mojo 'org.apache.maven.plugins:maven-site-plugin:2.0-beta-6:site'

[INFO] [DEBUG]   (f) siteDirectory = /Users/veleno/workspace/fractal-bf-parent/target/checkout/core/src/site
[INFO] [DEBUG]   (f) templateDirectory = /Users/veleno/workspace/fractal-bf-parent/target/checkout/core/src/site
[INFO] [DEBUG]   (f) xdocDirectory = /Users/veleno/workspace/fractal-bf-parent/target/checkout/core/xdocs
[INFO] [DEBUG]   - end configuration --
[INFO] [INFO] [site:site]
[INFO] [DEBUG] Mapped url: /Users/veleno/workspace/fractal-bf-parent/target/checkout/core/src/site to relative path: src/site
[INFO] [DEBUG] Reading site descriptor from src/site/site.xml
[INFO] [DEBUG] Parent project loaded ...
[INFO] [DEBUG] Mapped url: /Users/veleno/workspace/fractal-bf-parent/target/checkout/core/src/site to relative path: core/src/site
[INFO] [DEBUG] Reading site descriptor from core/src/site/site.xml
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [ERROR] FATAL ERROR
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] null

hopefully this helps debugging the problem somehow..

**Comment by jira-importer** [comment]
**[Valerio Schiavoni](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vschiavoni)** commented

For what it matters, it's using:
maven-release-plugin 2.0-beta-8

**Comment by jira-importer** [comment]
**[Valerio Schiavoni](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=vschiavoni)** commented

It seems that by adding a bogus \<url> element to the parent pom fixes the issue. The problem here is that I should modify an already tagged version of the SVN, which is quite disturbing.

**Comment by jira-importer** [comment]
**[Lukas Theussl](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ltheussl)** commented

See also MSITE-311
