### ISSUE TITLE
[DOXIASITETOOLS-108] NullPointerException when site URL is being generated

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-doxia-sitetools#389]
**[Marc Claessens](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=marc%20claessens)** opened **[DOXIASITETOOLS-108](https://issues.apache.org/jira/browse/DOXIASITETOOLS-108?redirect=false)** and commented

We have a parent POM where the site url is generated via the Maven Groovy plugin, unless it is explicitly defined in the child POM
i.e.

```xml
<site>
   <id>project-sites</id>
   <name>Our project Nexus server Site</name>
   <!-- URL is built dynamically by groovy plugin -->
</site>
...

<plugin>
   <groupId>org.codehaus.groovy.maven</groupId>
   <artifactId>gmaven-plugin</artifactId>
   <executions>
	<execution>
	<phase>pre-site</phase>
	<goals>
	   <goal>execute</goal>
	</goals>
	<configuration>
	<source>
          <![CDATA[
               if(!project.distributionManagement.site.url){
                    String version = new String(project.version)
                    String path = new String(project.artifactId)+'/'+version
                    project.distributionManagement.site.url ='dav:'+project.properties['siteBaseURL'] + path
               }
          ]]>

	</source>
	</configuration>
	</execution>
   </executions>
</plugin>
```

This leads to a NullPointerException in DefaultSiteTool.java:

```
at java.io.File.<init>(File.java:222)
at org.apache.maven.doxia.tools.DefaultSiteTool.urlEncode(DefaultSiteTool.java:1478)
at org.apache.maven.doxia.tools.DefaultSiteTool.getDistMgmntSiteUrl(DefaultSiteTool.java:1451)
```

The if statement in getDistMgntSiteUrl (for both methods) should test for null on project.getDistributionManagement().getSite().getUrl()

---
No further details from [DOXIASITETOOLS-108](https://issues.apache.org/jira/browse/DOXIASITETOOLS-108?redirect=false)

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Fixed in [r1310106](http://svn.apache.org/viewvc?view=revision&revision=1310106).

**Comment by jira-importer** [comment]
**[Marc Claessens](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=marc%20claessens)** commented

Please also update line 1461 to check for empty site URL.
Thanks in advance.

private static String getDistMgmntSiteUrl( Model model )
{
if ( model.getDistributionManagement() != null
&& model.getDistributionManagement().getSite() != null
&& model.getDistributionManagement().getSite().getUrl() != null )
{
...

**Comment by jira-importer** [comment]
**[Dennis Lundberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dennisl@apache.org)** commented

Fixed in [r1388197](http://svn.apache.org/viewvc?view=revision&revision=1388197).
